/* REXX */
/* LER MENSAGENS DO JES2 */
ADDRESS SDSF

"ISFEXEC LOG"     /* PAINEL LOG DO JES2/JES3 */

IF RC <> 0 THEN DO
  SAY "ERRO ISFEXEC LOG RC="RC
  EXIT RC
END

SAY "=== MENSAGENS JES2 ==="

DO I = 1 TO ISFROWS
   SAY ISFTIME.I " " ISFMSG.I
END
